### ISSUE TITLE
plot.somgrid: proposed improvement

### ISSUE THREAD

**Issue by ugroempi** [rwehrens/kohonen#10]
Hi Ron,

I propose a simple change to `plot.somgrid` that makes it much easier / possible to use the plots from the package in arrangements with `par(mfrow= ...` or layouts. I use this a lot in teaching SOMs (and I currently modify the function by `assignInNamespace` before using plot functionality). The proposal is to replace the function `eqscplot` from package MASS by a call to `plot` with the `asp=1` argument. Thus, the third command in function `plot.somgrid` should be changed to 

`plot(xlim, ylim, axes = FALSE, type = "n", xlab = "", ylab = "", asp=1, ...)`

Best, Ulrike

**Comment by rwehrens** [comment]
good proposal! I am including it in version 3.0.9
