### ISSUE TITLE
Wish: argument for code plot that allows to select part of the variables only

### ISSUE THREAD

**Issue by ugroempi** [rwehrens/kohonen#11]
Hi Ron,

here is another wish for code plots: it would be very nice to have an argument that allows to select only some of the components of the code vectors for plotting. Reason: I often find it quite difficult to interpret line plots and prefer segment charts of a few variables; this requires processing variables in several chunks. At the moment, I have to do these manually. An argument `variables` that would accept either position numbers or character strings of variable names would help me a lot for this task.

Best, Ulrike

**Comment by alexeifigueroa** [comment]
Replacing the codes with a subset works, it's not so elegant but it's just 3 lines, slicing with the variable names also works. 
`som.object.subset<-som.object`
`som.object.subset$codes[[1]]<-som.object$codes[[1]][,1:7]`
`plot(som.object.subset,
        shape = 'straight', type = 'codes', codeRendering = 'segments',palette.name = pal )`

**Comment by rwehrens** [comment]
I think I'd follow Alexei's solution here: since every data layer will have different variable names and numbers of variables it would require quite  a lot of checking. Moreover, the interface would be somewhat tedious.
