### ISSUE TITLE
SOM R codes plot issue

### ISSUE THREAD

**Issue by sathish-dream-ai** [rwehrens/kohonen#17]
> plot(supersom, type="codes") 
Warning message: In par(opar) : argument 1 does not name a graphical parameter

Sir, this is the error that I am facing now and the plot visualization is coming. pls help me to solve this issue. thanks in advance :)

**Comment by rwehrens** [comment]
Please add more details and a minimal reproducible example - there is 
nothing to work with here...

Cheers,
R

**Comment by sathish-dream-ai** [comment]
options(max.print = .Machine$integer.max)
set.seed(100)
dfthree = as.matrix(dftwo, "scale:center")
dfthree

{som_grid = somgrid(xdim=3, ydim=3, topo="rectangular", neighbourhood.fct = "gaussian", toroidal = FALSE)
supersom = som(dfthree, 
               grid=som_grid, rlen = 100,
               alpha=c(0.05,0.01),
               whatmap = NULL,
               maxNA.fraction = 0L,
               user.weights = 1,
               radius = 0.0005,
               dist.fcts = NULL,
               mode = "online",
               init,
               keep.data = TRUE)}


plot(supersom, type="changes")

plot(supersom, type="codes")

plot(supersom, type ="counts")


par(mfrow=c(3,3));
for (j in 1:9) { plot(supersom,type='property', property=as.data.frame(supersom$codes)[,j],main=colnames(data)[j],cex=0.8,palette.name=function(n, alpha = 1) {rainbow(n, end=4/6, alpha=alpha)[n:1]})}

above shows a code for plotting SOM in rstudio.cloud for free users.  warning error comes for the below code. visualization (given below in the attachment file with another doubt) is coming. 

given attached file contains a codes plot, I have a doubt left side fig has been plotted through written codes in rstudio.cloud and the right side fig ve been generated by thru xlstat kohonen R software package version. there are dissimilarities while I'm applying som model when we write codes, visualization will vary a bit while writing our code, but from the software, all the visualization from each circle will not change, is fixed with certain parameters ve been given.I do not know what is the reason behind it. som model have been shown above, and the data ve been already standardized as per the requirement. don't know whether any statistical tests are done inside the software like t.test or any other operators for fixing it. 
thanks 
![codes plot- rstudio](https://user-images.githubusercontent.com/46743355/188299508-88df522a-bd19-40b9-b292-33a803ca49be.png)

------------------------------------------------------------------------------------------------------------------------------
  plot(supersom, type="codes")
     Warning message: In par(opar) : argument 1 does not name a graphical
     parameter
-------------------------------------------------------------------------------------------------------------------------------

**Comment by rwehrens** [comment]
Hi Sathish,

I am not sure I understand what you mean, and the code below cannot be 
executed since I don't know what dftwo contains, but my guess is that 
you get different results when you run this code in R (Rstudio) and in 
excel (I had to look up xlstat, no idea you could run R code in excel). 
Is that correct?

The only thing I can think of is that the random number mechanism in 
excel is not the same as in R, and that you would basically be comparing 
two different maps in your plots. You could try to export your R map and 
load it in xlstat, and see if the plots are the same there. They should 
be the same when executed on different R platforms, say, a laptop and a 
desktop (running the same R version etc).

Let me know if I misunderstood...

Cheers,
R

**Comment by sathish-dream-ai** [comment]
library(kohonen)
library(dplyr)
library(vtable)


df = read.csv("sheetone.csv")
View(df)

data = df[,c(1:9)]

options(max.print = .Machine$integer.max)

dfone = df %>% mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))

dfone

View(dfone)

dftwo=round(dfone, digits=3)
dftwo
View(dftwo)



st(dftwo,
   summ = list(
     c('countNA(x)','min(x)','max(x)','mean(x)','sd(x)')
     
   ),
   summ.names = list(
     c('N','Min','Max','Mean','SD')
   )
)



dfthree = as.matrix(dftwo, "scale:center")
dfthree 

set.seed(1100)

som_grid = somgrid(xdim = 3, ydim=3, topo="rectangular", neighbourhood.fct = "gaussian", toroidal = FALSE)

supersom = som(dfthree, 
                grid=som_grid, rlen = 100,
                alpha=c(0.05,0.01),
                whatmap = NULL,
                maxNA.fraction = 0L,
                user.weights = 1,
                radius = 1,
                dist.fcts = NULL,
                mode = "online",
                init,
                keep.data = TRUE)

plot(supersom, type="changes")

plot(supersom, type="codes")

plot(supersom, type ="counts")


par(mfrow=c(3,3));
for (j in 1:9) { plot(supersom,type='property', property=as.data.frame(supersom$codes)[,j],main=colnames(dfthree)[j],cex=0.8,palette.name=function(n, alpha = 1) {rainbow(n, end=4/6, alpha=alpha)[n:1]})}


{res <- as.data.frame(cbind(supersom$unit.classif, supersom$distances))
colnames(res) <- c("Class","Distances")
res[,]
round(res, digits = 3)}


XLSTAT is a commercial tool, Kohonen R package is implemented through xlstat tool. Cannot do an experiment with xlstat. As u told, there may be random number mechanism issue with excel and R, can you pls guide me how to solve this error in R programming to get the exact result same as excel. If you need more details, I can sent an official email. Thanks :)

**Comment by sathish-dream-ai** [comment]
dftwo is the dataframe I named.

**Comment by rwehrens** [comment]
Hi there,

no, I can't help you solving problems with xlstat. Please restrict your 
questions to questions about the kohonen package.

All the best,
Ron

**Comment by sathish-dream-ai** [comment]
The problem is getting solved by changing the version of R.
