### ISSUE TITLE
Segfault in predict function

### ISSUE THREAD

**Issue by miranska** [rwehrens/kohonen#3]
Dear @rwehrens,
Thank you very much for you work on the `kohonen` package!

While trying to predict SOM cells for a new data, I’ve noticed that (in the case when `newdata` has signifcantly larger number of rows than the one on which the existing model was trained) `predict` function is causing segmentation fault as shown below.

```
> Rscript testcase.R

 *** caught segfault ***
address 0x10f359000, cause 'memory not mapped'

Traceback:
 1: .Call("kohonen_RcppMap", PACKAGE = "kohonen", data, numVars,     numNAs, codes, weights, distanceFunctions)
 2: RcppMap(data = newdata, numVars = nvars, numNAs = nNA, codes = codes,     weights = weights, distanceFunctions = dist.ptrs)
 3: map.kohonen(object, newdata = newdata, whatmap = whatmap.new,     ...)
 4: map(object, newdata = newdata, whatmap = whatmap.new, ...)
 5: predict.kohonen(som.m, newdata = test)
 6: predict(som.m, newdata = test)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault: 11
```

This issue manifests itself on MacOS (R v.3.3.2, kohonen v.3.0.2) and Linux (R v.3.4.1, kohonen v.3.0.4). Here is how environment looks like on Linux:
```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] kohonen_3.0.4

loaded via a namespace (and not attached):
[1] MASS_7.3-47    compiler_3.4.1 tools_3.4.1    Rcpp_0.12.12
```

A sample data and code needed to reproduce the issue are available in the attached file
[repro.zip](https://github.com/rwehrens/kohonen/files/1300915/repro.zip). Could you please take a look at this issue?

**Comment by rwehrens** [comment]
Thanks for the bug report - I can reproduce the issue.
When I convert test to a matrix the segfault disappears. I'll check whether there are any other sides to this issue, otherwise I will solve it by putting in another check.

**Comment by miranska** [comment]
Excellent, thank you!
