### ISSUE TITLE
New Rcpp does not need a Makevars file in the "kohonen" package

### ISSUE THREAD

**Issue by gilbertocamara** [rwehrens/kohonen#5]
Dear Ron 

Many thanks for the development of your nice package "kohonen". Our team at INPE (National Institute for Space Research - Brazil) is using the package sucessfully for satellite image time series data analysis. We would like to make a suggestion for an update to the package. The new Rcpp package is quite efficient. You can remove the files "Makevars" and "kohonen_init.c" in the /src directory, as they are no longer required in the new version of Rcpp. We also suggest you change the following line in the NAMESPACE file:
useDynLib(kohonen, .registration = TRUE)  
to a new line:
useDynLib(kohonen) 

Since this registration is already done by the Rcpp package. 

Thanks for your support,
Gilberto Camara
National Institute for Space Research, Brazil

**Comment by rwehrens** [comment]
It seems the Makevars file _is_ necessary for the parallel processing. It was removed in 3.0.6, but in 3.0.7 (now the develop version) we put it back.
