### ISSUE TITLE
Wish: possibility to specify NA color (for quality and other property maps)

### ISSUE THREAD

**Issue by ugroempi** [rwehrens/kohonen#9]
Hi Ron,

I had the need to change the color for empty cells to "white", because I wanted to use greyscale colors (because of lack of a color printer). For being able to achieve that, I had to modify the plot.kohprop function and use assignInNamespace on it, because it contains a hard-coded "gray". It would be very nice, if there were an argument for controlling that color.

Best, Ulrike

**Comment by rwehrens** [comment]
have added an argument na.color to the functions plotting properties and counts, respectively. I cannot easily imagine other functions to need this functionality but let me know if it is needed. At some point (that is, if we keep on adding functionality) it will become necessary to put all graphics parameters in a specific object but this is a step I'd like to postpone for as long as possible...
